name: Speakable
options:
  bundleIdPrefix: sh.lennon
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true
  developmentLanguage: en
  knownRegions:
    - en
    - zh-Hans

packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: "2.4.0"
  SwiftUIIntrospect:
    url: https://github.com/siteline/swiftui-introspect
    from: "26.0.0"
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: "2.8.1"

schemes:
  Speakable:
    build:
      targets:
        Speakable: all
        SpeakableTests: [test]
    run:
      config: Debug
      executable: Speakable
    test:
      config: Debug
      targets:
        - SpeakableTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "0.1.1"
    CURRENT_PROJECT_VERSION: "7"
    DEAD_CODE_STRIPPING: YES
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    SWIFT_EMIT_LOC_STRINGS: YES
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
    STRING_CATALOG_GENERATE_SYMBOLS: YES
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES

targets:
  Speakable:
    type: application
    platform: macOS
    sources:
      - path: Speakable/Sources
      - path: Speakable/Resources
    configFiles:
      Debug: Local.xcconfig
      Release: Local.xcconfig
    settings:
      base:
        INFOPLIST_FILE: Speakable/Resources/Info.plist
        PRODUCT_MODULE_NAME: Speakable
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_HARDENED_RUNTIME: YES
        COMBINE_HIDPI_IMAGES: YES
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"
      configs:
        Debug:
          PRODUCT_BUNDLE_IDENTIFIER: sh.lennon.Speakable.debug
          PRODUCT_NAME: Speakable Debug
        Release:
          PRODUCT_BUNDLE_IDENTIFIER: sh.lennon.Speakable
          PRODUCT_NAME: Speakable
    entitlements:
      path: Speakable/Resources/Speakable.entitlements
    dependencies:
      - package: KeyboardShortcuts
      - package: SwiftUIIntrospect
      - package: Sparkle

  SpeakableTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: SpeakableTests
    dependencies:
      - target: Speakable
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: sh.lennon.Speakable.tests
        BUNDLE_LOADER: $(TEST_HOST)
        GENERATE_INFOPLIST_FILE: YES
      configs:
        Debug:
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/Speakable Debug.app/Contents/MacOS/Speakable Debug
        Release:
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/Speakable.app/Contents/MacOS/Speakable
