name: Speakable
options:
  bundleIdPrefix: sh.lennon
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: "2.4.0"

schemes:
  Speakable:
    build:
      targets:
        Speakable: all
        SpeakableTests: [test]
    run:
      config: Debug
      executable: Speakable
    test:
      config: Debug
      targets:
        - SpeakableTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEAD_CODE_STRIPPING: YES
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    SWIFT_EMIT_LOC_STRINGS: YES

targets:
  Speakable:
    type: application
    platform: macOS
    sources:
      - path: Speakable/Sources
      - path: Speakable/Resources
    configFiles:
      Debug: Local.xcconfig
      Release: Local.xcconfig
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: sh.lennon.Speakable
        INFOPLIST_FILE: Speakable/Resources/Info.plist
        PRODUCT_NAME: Speakable
        PRODUCT_MODULE_NAME: Speakable
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_HARDENED_RUNTIME: YES
        COMBINE_HIDPI_IMAGES: YES
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"
    entitlements:
      path: Speakable/Resources/Speakable.entitlements
    dependencies:
      - package: KeyboardShortcuts

  SpeakableTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: SpeakableTests
    dependencies:
      - target: Speakable
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: sh.lennon.Speakable.tests
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/Speakable.app/Contents/MacOS/Speakable
        BUNDLE_LOADER: $(TEST_HOST)
        GENERATE_INFOPLIST_FILE: YES
